services:
  sms-provider:
    build: ./sms-provider
    container_name: sms-provider
    environment:
      PORT: 4001
      FAILURE_RATE: "0.2"
      MIN_LATENCY_MS: "50"
      MAX_LATENCY_MS: "250"
    ports:
      - "4001:4001"
    restart: unless-stopped

  my-server:
    build: ./my-server
    container_name: my-server
    depends_on:
      - sms-provider
    environment:
      PORT: 4000
      SMS_PROVIDER_BASE_URL: http://sms-provider:4001
      REQUEST_TIMEOUT_MS: "3000"
      RETRY_MAX_ATTEMPTS: "3"
      RETRY_BASE_DELAY_MS: "200"
      RETRY_MAX_DELAY_MS: "2000"
      LOG_FILE_PATH: /var/log/sms/sms.log
      STATS_CRON: "*/5 * * * *"
      STATS_TARGET_PHONE: "+96170000000"
      STATS_ENABLED: "true"
    volumes:
      - ./logs:/var/log/sms
    ports:
      - "4000:4000"
    restart: unless-stopped
